### ISSUE TITLE
Error migrating from cannon.js to cannon-es

### ISSUE THREAD

**Issue by aitormendez** [pmndrs/cannon-es#113]
I have a world with cannon.js physics working fine. When I try to migrate to cannon-es:

`import * as CANNON from 'cannon-es' ` instead `import CANNON from 'cannon' `

 I get an error in the `step()` function:

Uncaught TypeError: bodies[i].integrate is not a function

The `step()` function is:

`this.physicsWorld.step(1 / 60, this.experience.time.delta, 3)`

[Here is the function in context](https://github.com/aitormendez/tomasgarciapiriz/blob/main/site/web/app/themes/sage/resources/scripts/Experience/World/World.js#L63). 

I read the docs for the `step()` function: https://pmndrs.github.io/cannon-es/docs/classes/world.html#step but I can't find anything wrong (anyway, I have no much experience). What does that error means?

![Captura de pantalla 2021-11-19 a las 10 56 20](https://user-images.githubusercontent.com/2788577/142680897-35bc3d97-118b-43d6-a9b5-d13e8dc9a212.png)

**Comment by marcofugaro** [comment]
Hey, I can't test your setup, but I think you added a body somewhere which is not a cannon body.

Are you using cannon-es instead of cannon.js everywhere in your app?

If you can't find the source of the problem start from the [getting started example](https://pmndrs.github.io/cannon-es/docs/index.html) in the docs and build from there.

**Comment by aitormendez** [comment]
That was exactly the problem. I forgot to import cannon-es in the Floor class.

Thank you so much for point me in the right direction.
