### ISSUE TITLE
Deprecate fixedStep from World

### ISSUE THREAD

**Issue by krispya** [pmndrs/cannon-es#147]
I'm confused at why the `fixedStep()` method exists on World when all it does is call `step()`. I was tricked by this as I didn't expected `fixedStep()` to be interpolated, but it is! I suggest deprecating the duplicate method and making people use `step()` which allows for turning interpolation off.

**Comment by marcofugaro** [comment]
> It is confusing to me coming from engines like Unity which don't have interpolation on by default.

It is basically the same as using FixedUpdate from Unity, read the article I posted.

> Another gotchya is that even after enabling interpolation, it isn't enough to use body.position and body.quaternion, you need to use body.interpolatedPosition and body.interpolatedQuaternion

Nah man, you're confusing yourself. This is not interpolation, this is just "catching up". It runs more internal steps to make sure the simulation is run at the same time across every framerate. `interpolatedPosition` won't have any effect because the steps are run subsequently.

`interpolatedPosition` and `interpolatedQuaternion` are used instead when the timeStep is much greater, for example in multiplayer physics. Check out the [canvas_interpolation](https://pmndrs.github.io/cannon-es/examples/canvas_interpolation) example, we're simulating a slow connection by making the timestep half a second.

For the default usecase, using `.position` and `.quaternion` is correct.

**Comment by krispya** [comment]
Thanks for talking this through. I have read the article a few times in the past but maybe I'm not understanding fixed loop properly. The issue as I understand it with all fixed step loops is that there is time banking necessary, there is always some time left over as a remainder because the steps don't evenly divide with dt. This remainder is what I am using to interpolate in my own loop.

> Now consider that the majority of render frames will have some small remainder of frame time left in the accumulator that cannot be simulated because it is less than dt. This means we’re displaying the state of the physics simulation at a time slightly different from the render time, causing a subtle but visually unpleasant stuttering of the physics simulation on the screen.

> One solution to this problem is to interpolate between the previous and current physics state based on how much time is left in the accumulator:

Is this interpolation factor not what is being processed in the lerp/slerp loop right after the while loop here?https://github.com/pmndrs/cannon-es/blob/38775398362fabbfa90516b2f4f9664230c8388d/src/world/World.ts#L501-L506

**Comment by marcofugaro** [comment]
> Is this interpolation factor not what is being processed in the lerp/slerp loop right after the while loop here?

Nope, it's referring to the `.accumulator` property:
https://github.com/pmndrs/cannon-es/blob/38775398362fabbfa90516b2f4f9664230c8388d/src/world/World.ts#L479

Cannon has a max number of substeps the simulation can use to catch up, so we need to clear that time banking.

https://github.com/pmndrs/cannon-es/blob/38775398362fabbfa90516b2f4f9664230c8388d/src/world/World.ts#L498

**Comment by krispya** [comment]
Ah yeah! I think we might be misunderstanding each other. All I'm saying is that the way the step loop is written, the interpolation will always run on every physics body using the ratio of the time remainder on the accumulator and the delta time (which will always be there no matter how many substeps run since rAF varies). 

But this is far off topic so I'll close the ticket. Thanks for the discussion.
